name: Bug report 🐛
description: Create a bug report for Auto-GPT.
labels: ['status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ ### Before you continue
        Before you create this issue please join the [discord](https://discord.gg/autogpt) to discuss with our incredible members
        about your issue. You are more than to specify your issue in the [tech-support](https://discord.com/channels/1092243196446249134/1092275629602394184) channel.
  - type: checkboxes
    attributes:
      label: ⚠️ Search for existing issues first ⚠️
      description: >
        Please [search the history](https://github.com/Torantulino/Auto-GPT/issues)
        to see if an issue already exists for the same problem.
      options:
        - label: I have searched the existing issues, and there is no existing issue for my problem
          required: true
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        ⚠️ SUPER-busy repo, please help the volunteer maintainers.
        The less time we spend here, the more time we spend building AutoGPT.
        
        Please help us help you:
        - Does it work on `stable` branch (https://github.com/Torantulino/Auto-GPT/tree/stable)?
        - Does it work on current `master` (https://github.com/Torantulino/Auto-GPT/tree/master)?
        - Search for existing issues, "add comment" is tidier than "new issue"
        - Ask on our Discord (https://discord.gg/autogpt)
        - Provide relevant info:
          - Provide commit-hash (`git rev-parse HEAD` gets it)
          - If it's a pip/packages issue, provide pip version, python version
          - If it's a crash, provide traceback.
  - type: dropdown
    attributes:
      label: Which Operating System are you using?
      description: >
        Please select the operating system you were using to run Auto-GPT when this problem occurred.
      options:
        - Windows
        - Linux
        - MacOS
        - Other (Please specify in your problem)
  - type: dropdown
    attributes:
      label: GPT-3 or GPT-4
      description: >
        If you are using Auto-GPT with `--gpt3only`, your problems may be caused by
        the limitations of GPT-3.5. 
      options:
        - GPT-3.5
        - GPT-4
  - type: textarea
    attributes:
      label: Steps to reproduce 🕹
      description: |
        **⚠️ Issues that we can't reproduce will be closed.**
  - type: textarea
    attributes:
      label: Current behavior 😯
      description: Describe what happens instead of the expected behavior.
  - type: textarea
    attributes:
      label: Expected behavior 🤔
      description: Describe what should happen.
  - type: textarea
    attributes:
      label: Your prompt 📝
      description: |
        If applicable please provide the prompt you are using. Your prompt is stored in your `ai_settings.yaml` file.
      value: |
        ```yaml
        # Paste your prompt here
        ```
  - type: textarea
    attributes:
      label: Your Logs 📒
      description: |
        If applicable please include your error logs. You can find them at `logs/error.log`.
        This will help us understand your issue better!
      value: |
        ```
        <insert your logs here>
        ```